package helper;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;

public class PageEventHelper extends PdfPageEventHelper {
    
    private String reportType;
    private String currentUser;
    private String headerText;
    private String footerText;
    private PdfTemplate totalPagesTemplate;
    private BaseFont bfBold;
    private BaseFont bfItalic;
    
    public PageEventHelper(String reportType, String currentUser, String headerText, String footerText) {
        this.reportType = reportType;
        this.currentUser = currentUser;
        this.headerText = headerText;
        this.footerText = footerText;
        try {
            this.bfBold = BaseFont.createFont(BaseFont.HELVETICA_BOLD, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
            this.bfItalic = BaseFont.createFont(BaseFont.HELVETICA_OBLIQUE, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    @Override
    public void onOpenDocument(PdfWriter write, Document doc) {
        totalPagesTemplate = write.getDirectContent().createTemplate(30, 16);
    }
    
    @Override
    public void onEndPage(PdfWriter write, Document doc) {
        PdfContentByte cb = write.getDirectContent();
        
        float margin = 120f;
        float headerY = doc.top() + (margin / 2);
    
        // Print web.xml Header
        cb.beginText();
        cb.setFontAndSize(bfBold, 10);
        cb.showTextAligned(Element.ALIGN_CENTER, headerText, (doc.right() + doc.left()) / 2, headerY, 0);
        cb.endText();

        // Print Report Title
        cb.beginText();
        cb.setFontAndSize(bfBold, 14);
        cb.showTextAligned(Element.ALIGN_CENTER, reportType, (doc.right() + doc.left()) / 2, headerY - 20, 0);
        cb.endText();

        // Print Logged-in User and web.xml Footer
        cb.beginText();
        cb.setFontAndSize(bfItalic, 10);
        cb.showTextAligned(Element.ALIGN_LEFT, "Generated by: " + currentUser, doc.left(), doc.bottom() - 15, 0);
        cb.showTextAligned(Element.ALIGN_CENTER, footerText, (doc.right() + doc.left()) / 2, doc.bottom() - 15, 0);
        cb.endText();

        // Print Page x of y Pagination
        String pageText = "Page " + write.getPageNumber() + " of ";
        float textSize = bfItalic.getWidthPoint(pageText, 10);
        
        cb.beginText();
        cb.setFontAndSize(bfItalic, 10);
        float textBase = doc.bottom() - 15;
        float textX = doc.right() - 40; 
        
        cb.setTextMatrix(textX, textBase);
        cb.showText(pageText);
        cb.endText();

        cb.addTemplate(totalPagesTemplate, textX + textSize, textBase);
    }

    @Override
    public void onCloseDocument(PdfWriter writer, Document document) {
        totalPagesTemplate.beginText();
        totalPagesTemplate.setFontAndSize(bfItalic, 10);
        totalPagesTemplate.setTextMatrix(0, 0);
        totalPagesTemplate.showText(String.valueOf(writer.getPageNumber()));
        totalPagesTemplate.endText();
    }
}